{{- if not (lookup "v1" "ServiceAccount" .Release.Namespace "kubemq-operator") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubemq-operator
  namespace: {{ .Release.Namespace }}
{{- end }}
---
{{- if not (lookup "v1" "ServiceAccount" .Release.Namespace "kubemq-cluster") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubemq-cluster
  namespace: {{ .Release.Namespace }}
{{- end }}
