{{- if .Values.operator.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubemq-operator
  namespace: {{ .Release.Namespace }}
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubemq-cluster
  namespace: {{ .Release.Namespace }}
