version: '3'
vars:
  NAMESPACE: kubemq
  SOURCE: kubemq-charts

tasks:
  release:
    cmds:
      - helm package kubemq-crds -d ./docs
      - helm package kubemq-controller -d ./docs
      - helm package kubemq-cluster -d ./docs
      - helm package kubemq-bridges -d ./docs
      - helm package kubemq-targets -d ./docs
      - helm package kubemq-sources -d ./docs
      - helm repo index ./docs
  install:
    cmds:
      - cmd: helm install --create-namespace -n kubemq kubemq-crds ./kubemq-crds
      - cmd: helm install --wait -n kubemq kubemq-controller ./kubemq-controller
      - cmd: helm install --wait -n kubemq kubemq-cluster --set key=d7da1859-2924-4c45-8cf8-12c7e6b4b2c0 kubemq-charts/kubemq-cluster
  delete:
    cmds:
      - cmd: helm uninstall -n kubemq kubemq-cluster
      - cmd: helm uninstall -n kubemq kubemq-controller
      - cmd: helm uninstall -n kubemq kubemq-crds
