version: '3'
vars:
  NAMESPACE: kubemq3
  SOURCE: kubemq-charts

tasks:
  release:
    cmds:
      - helm package kubemq -d ./docs
      - helm package connector -d ./docs
      - helm package operator -d ./docs
      - helm repo index ./docs
  install:
    cmds:
#      - cmd: helm repo add kubemq-charts https://kubemq-io.github.io/charts
#        ignore_error: true
      - cmd: helm repo update
        ignore_error: true
      - cmd: kubectl create ns {{.NAMESPACE}}
        ignore_error: true
      - cmd: helm install kubemq-operator {{.SOURCE}}/operator --namespace={{.NAMESPACE}}
        ignore_error: true
      - cmd: helm install kubemq-cluster {{.SOURCE}}/kubemq --namespace={{.NAMESPACE}}
        ignore_error: true
      - cmd: helm install kubemq-dashboard {{.SOURCE}}/dashboard --namespace={{.NAMESPACE}}
        ignore_error: true
      - cmd: helm install kubemq-bridges {{.SOURCE}}/connector --namespace={{.NAMESPACE}}
        ignore_error: true
  delete:
    cmds:
      - cmd: helm delete kubemq-cluster --namespace={{.NAMESPACE}}
        ignore_error: true
      - cmd: helm delete kubemq-dashboard --namespace={{.NAMESPACE}}
        ignore_error: true
      - cmd: helm delete kubemq-bridges --namespace={{.NAMESPACE}}
        ignore_error: true
      - cmd: helm delete kubemq-operator --namespace={{.NAMESPACE}}
        ignore_error: true
