operatorImage: docker.io/kubemq/kubemq-operator:latest
kubemqImage: docker.io/kubemq/kubemq:latest
connectorTargetsImage: kubemq/kubemq-targets:latest
connectorSourcesImage: kubemq/kubemq-sources:latest
connectorBridgesImage: kubemq/kubemq-bridges:latest