apiVersion: core.k8s.kubemq.io/v1beta1
kind: KubemqConnector
metadata:
  name: {{ include "connector.fullname" . }}
  labels:
    app: {{ include "connector.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: targets
{{ toYaml .Values | indent 2 }}
